
FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl

COPY requirements.txt .
RUN pip install -r requirements.txt

# Don't copy code files - they will be mounted as a volume
CMD ["python", "app.py"]